"""added user location

Revision ID: 21b3300a8b2e
Revises: 9e5a9af7edfc
Create Date: 2018-08-24 16:54:48.300678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b3300a8b2e'
down_revision = '9e5a9af7edfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_location', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_location')
    # ### end Alembic commands ###
