"""records

Revision ID: 38d22f26e3af
Revises: 7aca50b057ed
Create Date: 2018-09-02 15:05:20.553753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d22f26e3af'
down_revision = '7aca50b057ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('study', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_records_study'), 'records', ['study'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_records_study'), table_name='records')
    op.drop_column('records', 'study')
    # ### end Alembic commands ###
