"""record form fields added

Revision ID: 7aca50b057ed
Revises: bbb64ed3370e
Create Date: 2018-08-28 16:52:41.074620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aca50b057ed'
down_revision = 'bbb64ed3370e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('end', sa.DateTime(), nullable=True))
    op.add_column('records', sa.Column('marijuana', sa.Boolean(), nullable=True))
    op.add_column('records', sa.Column('other', sa.Boolean(), nullable=True))
    op.add_column('records', sa.Column('start', sa.DateTime(), nullable=True))
    op.add_column('records', sa.Column('tobacco', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'tobacco')
    op.drop_column('records', 'start')
    op.drop_column('records', 'other')
    op.drop_column('records', 'marijuana')
    op.drop_column('records', 'end')
    # ### end Alembic commands ###
